services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    networks:
      - pytrace
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - pytrace
    restart: always

networks:
  pytrace:
    driver: bridge
